### ISSUE TITLE
Removing Sun does not remove all data. creates Sun.001

### ISSUE THREAD

**Issue by martinsh** [PhysicalAddons/physical-starlight-and-atmosphere#1]
"When deleting all Suns there seems to be an issue, as the next sun being added will be called Sun.001 then when you delete everything and start again it will say Sun.002, 1 upside is it seems to be working from the start now, that was an oversight the first go. But you can only get things working again by manually entering the name of the sun as "Sun" if you end up deleting on accident"

**Comment by karlisup** [comment]
Fixed in [version 1.2.3](https://starlight-manual.readthedocs.io/en/latest/release-notes/#123-released-20082020).
