### ISSUE TITLE
When starting an F12 render the exposure is being reset

### ISSUE THREAD

**Issue by ogierm** [PhysicalAddons/physical-starlight-and-atmosphere#11]
**Describe the bug**
When I start a render or change the frame (playback) the exposure is being reset to the Blender default.

**General information**
- Blender version: 2.90
- Engine: Cycles
- Operating System: Windows 10
- Other info that could be useful: [e.g. CPU, GPU, etc.]:
Core i5 3570K
GTX 970

**To Reproduce**
1. Open a new scene and enable Physical Starlight
2. Hit render

**Screenshots**
![2020-06-06_22-28-15](https://user-images.githubusercontent.com/29630575/83953966-3b572c80-a845-11ea-8f67-600b7a88552c.gif)

**Comment by karlisup** [comment]
Hi, this should be fixed with PSA v1.2.2 bugfix.
