### ISSUE TITLE
Cant use the Addon on more than one Scene / Exposure -6.000 overexposed output MultilayerEXR

### ISSUE THREAD

**Issue by LennartSolik** [PhysicalAddons/physical-starlight-and-atmosphere#16]
**Describe the bug**

The node in the world node editor gets disabled if you use the addon on more than one scene.

Another thing i noticed is that on the output from the exr in programs like After Effects or Affinity the Exposure jumps back to 0 and the Final images are overexposed and need an adjustment layer in the external Software to set the exposure back to -6. 

The worst thing is even if i put a custom node before the Multilayer Output that sets the exposure once again to -6.000 the final images in the external software are now on the correct exposure but the Alpha masks are broken. To fix this i had to seperate rgba and set the expose from the alpha mask to 0 and then combine the rgba again. The nodetree i used is attached below.

**General information**
- Blender version: 2.8.2.6
- Engine: Evee or Cycles
- Operating System: Win10 x64

**To Reproduce**

For example:

a Background scene for only the athmosphere and a Foreground scene with objects that need to have a transparent background but recieve the light from the addon.

When the addon gets enabled on the Background scene and then on the Foreground scene with transparancy checked in the Film tab the Addon node dissapears from the Background scene.

I now have to use a workaround with a holdout plane to eliminate the athmosphere to come trough on some layers and have to use the Add blend mode instead of alpha over to merge the layers. Still not ideal.

seems to be a Bug like the Eposure setting not resetting after disabling the addon. I copy and pasted the Athmospheric node from one scene to another and didnt touch the button to enable / disable the addon. It now works as expected. 

**Screenshots**
https://imgur.com/a/XjT1xGH

**Comment by karlisup** [comment]
Hi @LennartSolik,
> The node in the world node editor gets disabled if you use the addon on more than one scene.

I'll add this to the known issues and we will prioritize it one day or another.

Regarding the exposure jumping issue. Next bugfix will introduce a checkbox that will allow toggling on the use of the real-world physical values and by default, more artistic values will be used. But more important we decided not to fiddle with exposure as it breaks the workflow for people who use other addons which also modify exposure. I hope that this small change will fix your issue.

**Comment by karlisup** [comment]
Hi! I did create a new bug only regarding the fact that addon doesn't work properly when working with multiple scenes. I'll close this issue as this is a hybrid from 2 issues - one that is closed regarding exposure (#11, #8) and one that has to be prioritized (#26).

@LennartSolik I would really appreciate your input on issue #26 about how would you expect this addon work with multiple Scenes as I've no experience working in such.
