### ISSUE TITLE
Material Fog really Vram intensive

### ISSUE THREAD

**Issue by LennartSolik** [PhysicalAddons/physical-starlight-and-atmosphere#17]
**Describe the bug**
Scene jumps from 3GB to over 7GB Vram after using Material Fog. ~about 15 Materials. In the Documentation it says: very memory efficient, does not consume video memory - works great on integrated GPUs 

**General information**
- Blender version: [e.g. 2.8.2.6]
- Engine: EEVEE, Cycles
- Operating System: Win10 x64

**Comment by karlisup** [comment]
Hi @LennartSolik ,
Thank you for reporting this bug! Also, this one will be put in the known bugs section and addressed. The fog is more in an experimental stage and hasn't been tested for the performance yet.

**Comment by karlisup** [comment]
In 1.4.2 shader node setup is completely redone. Also, we added a user interface that allows choosing between manually applied fog and automatically applied fog. Last but not least now when node setup is modified, we add a flag that prevents our script from tampering with this modified node setup (this prevents loss of custom node setup).
It is still RAM intensive but can handle much more than before as sun calculation is separated from fog calculation.
