### ISSUE TITLE
v1.2 release zip on Blender Market is broken.

### ISSUE THREAD

**Issue by ogierm** [PhysicalAddons/physical-starlight-and-atmosphere#18]
All of these should be wrapped inside of a folder called `physical-starlight-atmosphere`, otherwise the installation will fail.
![image](https://user-images.githubusercontent.com/29630575/85932712-b5238880-b8ce-11ea-9650-4337ed07630a.png)

**Comment by karlisup** [comment]
My apologies, I updated the structure and reuploaded it.
