### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by pdesopo** [PhysicalAddons/physical-starlight-and-atmosphere#19]
I have installed the latest version 1.2.1, and I'm getting this error

`Traceback (most recent call last):
  File "C:\...\E_cycles_2.90_v20200622_win\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'physical-starlight-atmosphere-1'`

**Comment by karlisup** [comment]
Duplicate of #18
