### ISSUE TITLE
Physical Starlight not working in Blender 2.83

### ISSUE THREAD

**Issue by PhillipBerg** [PhysicalAddons/physical-starlight-and-atmosphere#20]
The add physical starlight-on is not working in the new Blender release 2.83.

When you activate it the screen just stays grey. 

![Blender2 83_Starlight Error](https://user-images.githubusercontent.com/67714991/86296579-0eeac200-bbf1-11ea-9f44-92ecd920c264.JPG)

**Comment by karlisup** [comment]
Hi @PhillipBerg ,
I can't manage to reproduce this bug. Have you given a try to the [Installation Troubleshooting](https://starlight-manual.readthedocs.io/en/latest/installation/#installation-troubleshooting) section in the documentation?

**Comment by martinsh** [comment]
you need to enable render view in the viewport. then it will show the sky

![uploads_1578526409933-Screen+Shot+2020-01-09+at+10 32 35+am__01](https://user-images.githubusercontent.com/11915915/87442494-0a64d700-c5fd-11ea-9655-aeb5fcf04f4a.png)

**Comment by karlisup** [comment]
Hi, I'll close this issue currently. Let's reopen it if the issue occurs again.

**Comment by PhillipBerg** [comment]
Hi again,

Me and other people are experiencing an error when trying to use  the viewport render animation function.

The screen and renders turn out almost completely black even though it looks fine in the viewport.

Do you know what causes this and how to fix it?

Best,
