### ISSUE TITLE
Azimuth or elevation modification not possible with Blender 2.82a

### ISSUE THREAD

**Issue by croucrou** [PhysicalAddons/physical-starlight-and-atmosphere#21]
**Describe the bug**
Open a new  blender file with the default cube. 
Enable atmosphere
Try to change manually elevation or azimuth
Blender crashes

Any other parameter change is ok. Atmosphere addon works well. But I can't modify elevation or azimuth values

**General information**
- Blender version: 2.82a
- Engine:  Evee and Cycles
- Operating System: Windows 10
- Other info that could be useful: CPU: i7-7700 GPU: GTX 1070

**Comment by croucrou** [comment]
same test (default cube) with the following configs:

1) blender v2.83.2 + addon v1.2.1: can't modify sun position (azimuth or elevation ) via UI gizmo or SunPosition addOn.
Blender crashes

2) blender v2.82.a + addon v1.2.1: can't modify sun position (azimuth or elevation ) via UI gizmo or SunPosition addOn.
Blender crashes

3) blender 2.82.a AND v2.83.2 + addon v1.1: OK no crash

**Comment by karlisup** [comment]
Hi @croucrou,
Thank you for your patience! Unfortunately, I couldn't reproduce the issues you are reporting. 
> Try to change manually elevation or azimuth

I tried sliding it, entering values, and hitting enter and also using `Sun Position` addon, but none gave the reported results. Is this issue still bothering you or have you find a temporary or permanent fix for it? Is the console giving any errors?

**Comment by karlisup** [comment]
I'll currently close the issue as inactive, but if you manage to reproduce the issue, just drop the line and I'll get back to you.
