### ISSUE TITLE
Fireflys in viewport and rendered image

### ISSUE THREAD

**Issue by nikocraft** [PhysicalAddons/physical-starlight-and-atmosphere#22]
**Describe the bug**
Fireflys are visible on in both viewport and rendered images.

**General information**
- Blender version:
2.8.3
- Engine:
Cycles, Feature Set: Supported

- Operating System:
Win 10

- Other info that could be useful: [e.g. CPU, GPU, etc.]: 
GPU Rendered

**To Reproduce**
Turn on Physical Atmosphere, add a plane. Use these settings
![image](https://user-images.githubusercontent.com/443080/88493645-8e7e6d80-cfb2-11ea-82a6-fa1754bcd8eb.png)

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![image](https://user-images.githubusercontent.com/443080/88493382-12375a80-cfb1-11ea-97e8-5d6604a8640b.png)

Noticable even in the viewport

![image](https://user-images.githubusercontent.com/443080/88493591-37789880-cfb2-11ea-9819-3417212a5aa2.png)

**Comment by karlisup** [comment]
Hi @nikocraft,
Unfortunately using Cycles in combination with scenes that have low light levels will cause fireflies. Currently, I can suggest only widely known solutions mentioned in this [StackExchange post](https://blender.stackexchange.com/questions/1703/how-to-reduce-fireflies-in-cycles).

I reproduced the bug and the solution I thought most effective was playing with Clamping (under Reder Properties). Although the output sun color has changed drastically I managed to get rid of the fireflies. It may be a solution in some cases but in some would not solve the issue at all.

![clamped-sun](https://user-images.githubusercontent.com/3999661/88638593-5e26f400-d0c4-11ea-85be-81007fef577f.png)
![clamped-sun2](https://user-images.githubusercontent.com/3999661/88638602-60894e00-d0c4-11ea-8b5b-8a2913ed2b0b.png)

Did you have an opportunity to try Bkjernisted [proposed solutions](https://blenderartists.org/t/physical-starlight-and-atmosphere-addon-for-2-8-v1-2/1185314/460):
* using Optix and 600 samples or less
* using super image denoiser

Would be very interested if they produced better results.

**Comment by nikocraft** [comment]
I'll test your suggestion today and will let you know the results.

**Comment by nikocraft** [comment]
I'll test Bkjernisted  proposal today as well, thanks for feedback! 👍

**Comment by nikocraft** [comment]
Hi @karlisup I tried Bkjernisted solution. With between 600-900 samples basically 99-100% of fireflys are gone. With 64 samples and Super Image Denoiser, I get again 99% fireflys gone, if I increase samples to 128 then it's very hard to get any fireflys. Here is 64 samples and only one blured out firefly. 

![image](https://user-images.githubusercontent.com/443080/88724490-e0e29a00-d12a-11ea-9ebb-a52ba3757461.png)

Same render with 90 samples and I can't spot any fireflys, this is thanks to Super Image Denoiser which wipes them out after it runs. 

![image](https://user-images.githubusercontent.com/443080/88724548-feafff00-d12a-11ea-89eb-09e92ebc6399.png)

**Comment by karlisup** [comment]
I am really glad that these solutions worked out!

**Comment by schroef** [comment]
What some other render engines do, is render the image larger and than scale down the image. My old render engine Thea Render had this build it. it would render at 2x or 4x. Yes takes longer, but really is good getting away with these fire flies. you can always do some tests. If the scene is not to difficult and detailed, you can always retouch it later in a photo-edit application. Or use a blurred image with painted mask to mask those parts out
