### ISSUE TITLE
Atmosphere affects all other lighting entities despite it is de-activated

### ISSUE THREAD

**Issue by aavenr** [PhysicalAddons/physical-starlight-and-atmosphere#23]
After I deactivate Atmosphere, all lighting-related entities need far stronger values to achieve the same results as before Atmosphere was activated. 

**General information**
- Blender version: 2.83.3
- Eveee
- Operating System: Windows 10

**To Reproduce**
Activate Atmosphere and play around with the settings
Deactivate it again. It will visually remove the sun from the renderer and in the Outliner, change the World nodes, etc so everything seems fine. 
Howeever, all lighting entities are noticeably dimmer now. 
- Notice how your the Background node Strength value (connected to your HDRI) needs to be amped 30x to get the same effect now. The point or area lights now need to be 10x as strong for them to be even visible and if you add a sun, it needs to have 10x more intensity to have noticeable effect.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by LennartSolik** [comment]
It happends because the Exposure is stuck at -6.000. Its already a known bug. Should be fixed at the next update. Simply set the Exposure setting back to original value (right click / reset to default value)

**Comment by karlisup** [comment]
Hi,
What addon version are you using currently? Is it 1.2.2?
![image](https://user-images.githubusercontent.com/3999661/89793363-75d39300-db2e-11ea-8aee-139ede67df4c.png)

**Comment by aavenr** [comment]
Hi, 

It's 1.2. Thanks for the tip! I submitted a question on Blender Market as to where I can find the 1.2.2 update link for existing customers.

**Comment by karlisup** [comment]
Hi, in BlenderMarket you can find all the addons you have bought going to `Account > Orders`. There you will find a list with the option `Go To Downloads`. Hope it helps ;)
