### ISSUE TITLE
Lighting issue (Day/Night Cycle animation)

### ISSUE THREAD

**Issue by pac0master** [PhysicalAddons/physical-starlight-and-atmosphere#27]
**Describe the bug**
I had a weird bug happening where I have manually set the Azimuth and Elevation of the sun, but for some reason, whenever I click somewhere in the timeline  the lighting doesn't update properly, instead it reverts back to its default value or something.
I have to move on a different frame to update it.

**General information**
- Blender version: 2.90.0
- Addon version: 1.2.3
- Engine: Cycle
- Operating System:  Windows 10
- Other info that could be useful: GPU, Nvidia RTX 2070

**To Reproduce**
As described,  I click somewhere random in the timeline and it becomes daytime, I move it by one frame and it becomes the right thing.
https://www.youtube.com/watch?v=L26jAfiGwC8&feature=youtu.be

**Screenshots**
https://i.imgur.com/T6X1pYa.png

Meanwhile, had a lot of issues trying to make a proper Day/Night Cycle, but it may be caused by other addons, I don't know.
All I know is for no apparent reasons, the sun doesn't seem to move in the rendering or it suddenly stop after some frame.

**Comment by karlisup** [comment]
Hi @pac0master,
Thank you for reporting this issue and taking your time to take the video as it really helps to understand the issue. I will try to find time to reproduce the bug and get back to you ASAP.

**Comment by karlisup** [comment]
Hi @pac0master,
It took quite a while to understand the issue. Thank you for your patience! We did improve node setup to improve performance and fixed a few sun rendering bugs on the way. Could you try out 1.4.2-beta and report if such behavior still persists?
