### ISSUE TITLE
Eclipse like sun artifact when looking through refracted material

### ISSUE THREAD

**Issue by Henrylee54** [PhysicalAddons/physical-starlight-and-atmosphere#29]
When looking through a refracted material, like glass, there is an artifact that inversely follows the sun while close to the horizon. It looks like an eclipse. 

**General information**
- Blender version: [e.g. 2.90]
- Addon version: 1.3
- Engine: Evee
- Operating System: Windows 10
- Other info that could be useful: RTX 2070 Super

**To Reproduce**
Test a see through material with full transmission and set the sun's elevation to be near sunset.

**Screenshots**

![refraction issue](https://user-images.githubusercontent.com/67246523/100016984-10c74480-2d8f-11eb-9be9-f7b9ac251190.png)

**Comment by Henrylee54** [comment]
This can be fixed by slightly raising the roughness when using a texture plugged into the roughness.

**Comment by karlisup** [comment]
Hi @Henrylee54,
Thank you for your patience! Unfortunately, this is how light source implementation in the Eevee rendering engine is. Thank you for reporting the issue!
