### ISSUE TITLE
Default Presets not showing up / Can't Save Presets 2.91

### ISSUE THREAD

**Issue by rausbaus** [PhysicalAddons/physical-starlight-and-atmosphere#32]
Default presets not showing up, can't save presets

**General information**
- Blender version: 2.91
- Addon version: 1.3
- Engine: Eevee
- Operating System: Windows10
- Other info that could be useful: GPU

**To Reproduce**
Select Preset dropdown, says *Missing Paths*

**Screenshots**
![Screenshot 2020-12-29 143452](https://user-images.githubusercontent.com/60794910/103312553-0d088c80-49e3-11eb-8bb1-6f4750ca241d.png)

**Comment by karlisup** [comment]
Hi @rausbaus,
Thank you for your patience!  It may be an update bug when you update from an older version to the new one without removing the previous version. Can you try full reinstall as mentioned in the [documentation](https://www.physicaladdons.com/psa/updating/) and let me know if it is working for you?

**Comment by karlisup** [comment]
I'll close this issue as it's currently inactive and potentially fixed. If the issue persists, feel free to reopen this ticket.

**Comment by rausbaus** [comment]
Hey there, just getting back to seeing this and trying a full reinstall. Unfortunately it didn't work - I tried multiple times, including removing the the addon folder from the Blender files manually. Not sure where the issue could be... I guess I'll just wait for the next update lol. Love the product itself btw!

**Comment by karlisup** [comment]
> Love the product itself btw!

It means a lot and thank you for getting back! It would help me to understand the issue better if you could provide any of this information:
1. Can you see any errors in the console?
  1.1 open Blender console (Window > Toggle System Console)
  1.2 disable and enable the addon
2. Can you find your Blender addons under any of these two paths? 
  2.2 `C:/Users/<your-username>/AppData/Roaming/Blender Foundation/Blender/<blender-version-here>/scripts/addons/physical-starlight-atmosphere`
  2.3` C:/Program Files (x86)/Steam/steamapps/common/Blender/<blender-version-here>/scripts/addons/physical-starlight-atmosphere`
3. Do you have the `/presets` folder with 4 files within in `physical-starlight-atmosphere` folder?

**Comment by rausbaus** [comment]
I fixed it! After following your first point, I found that the Blender system console log said I didn't have permissions to this folder: C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\presets. Apparently this folder needed permissions so the the presets in /addons/physical-starlight-atmosphere could be accessed and saved over. I can now also save my own presets. 

So glad I have access to them btw, the retrowave preset is amazing and I would have never thought something like that would have been possible. Any more presets in the future by chance? : ) Thanks for your help!

**Comment by karlisup** [comment]
I am glad that it worked out for you and happy to hear that you like the new features. We haven't planned yet any new releases of presets as there are more urgent tasks on hand, but we have plenty of preset ideas to execute for the future.
