### ISSUE TITLE
Addon toolbar not showing up in all scenes

### ISSUE THREAD

**Issue by AlbertYuyustein** [PhysicalAddons/physical-starlight-and-atmosphere#35]
I have four scenes in Blender, the addon toolbar shows up in the first three scenes but not the last one.
Disabling and enabling and restarting Blender did not help.

- Blender version: 2.91.0
- Windows 10

**Comment by AlbertYuyustein** [comment]
Ivy Gen Toolbar is also missing so its probably an external issue

**Comment by karlisup** [comment]
Hi Albert,
Thank you for reporting the issue. It's an issue of our addon and will be tackled in upcoming bugfixes. You can follow the [issue here](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/26).
