### ISSUE TITLE
No module named 'physical-starlight-atmosphere1'

### ISSUE THREAD

**Issue by majicmane** [PhysicalAddons/physical-starlight-and-atmosphere#39]
**Describe the bug**
[After I add the 1.3.0 zip file physical starlight shows up with a checkbox. When I try to check the box I get this error "C:Program Files\Blender Foundation 2.92\2.92\scripts\modules\addon_utils.py", line351, in enable mod=_import_(module_name)
![2021-04-13 (1)](https://user-images.githubusercontent.com/82487210/114647981-00ffbc80-9cac-11eb-9fba-133a7733ded5.png)
![2021-04-13 (1)](https://user-images.githubusercontent.com/82487210/114648014-0e1cab80-9cac-11eb-8dda-bdfe9f79c54b.png)
![2021-04-13 (1)](https://user-images.githubusercontent.com/82487210/114648053-255b9900-9cac-11eb-863b-d45eda74e80a.png)
![2021-04-13 (1)](https://user-images.githubusercontent.com/82487210/114648067-2b517a00-9cac-11eb-8fa5-1ac3197a2d08.png)

 ]

**General information**
- Blender version: [2.9.2]
- Addon version: [ 1.3.0]
- Engine: [either]
- Operating System: [Windows 10}
: 

**To Reproduce**
[Add on the zip and then physical starlight shows up in the menu and you try to check the box you will get the traceback error]

**Comment by karlisup** [comment]
Hi Rob,
Thank you for your patience! Did you already find a solution? There is an FAQ section on the addon documentation page that targets exactly [installation issues](https://www.physicaladdons.com/psa/faq/#physical-starlight-and-atmosphere-is-not-installing).
As I mentioned in blendermarket reply it seems wrong that your folder name is `physical-starlight-atmosphere1`, it should be without number postfix. Have you tried installing 1.4.2-beta or 1.3.1 versions?
