### ISSUE TITLE
Problems with star texture and rotation

### ISSUE THREAD

**Issue by benthillerkus** [PhysicalAddons/physical-starlight-and-atmosphere#4]
**Describe the bug**
When you provide a star texture it rotates with the sun - which is fine. The only issue is that when you don't have a sky texture, but a regular HDRI, ground will be up at night. So it would be nice to have a slider or something to counter rotate I think.

**General information**
- Blender version: 2.82
- Engine: EEVEE
- Operating System: Manjaro Linux

**Comment by karlisup** [comment]
Hi, @ogierm!
Sorry, I am a bit confused about what is the difference between regular HDRI and sky texture. Could you explain to me what do you mean by these terms? If you would provide information on how I could reproduce this, it would help a lot. Thank you in advance!

**Comment by benthillerkus** [comment]
The issue is that if you rotate the sun, the HDRI rotates aswell, so you might end up having the floor in the HDRI on the horizon

**Comment by karlisup** [comment]
Sorry, but I still can't get your point. Let me go step by step and give an example:
> The issue is that if you rotate the sun, the HDRI rotates aswell

 So I upload `star.png` under `Stars > Texture` and then I rotate sun and stars move along it. 
> you might end up having the **floor in the HDRI on the horizon**

This is the part I cannot understand. What do you mean by having the `floor in HDRI on the horizon`?  Could you make a screenshot, please with an example? I am sure that it would help me to understand the case.

**Comment by karlisup** [comment]
Issue closed as inactive.
