### ISSUE TITLE
shadow only emited on first frame, after first frame shadow dissapear

### ISSUE THREAD

**Issue by mafiavc** [PhysicalAddons/physical-starlight-and-atmosphere#40]
**Describe the bug**
this is super weird on first frame look normal but after I switch to another frame the shadow dissapear when I render it, but in render mode I still can see the shadow on any frame,this only happend after I render it,only first frame the shadow look normal even in render result

**General information**
- Blender version: [2.9]
- Addon version: [1.3]
- Engine: [Evee ]
- Operating System: [Windows 10]
- Other info that could be useful: [e.g. CPU, GPU, etc.]:

**Comment by karlisup** [comment]
Hi @walhackmaster,
Thank you for your patience! In PSA v1.4.2-beta we applied multiple animation performance improvements and also fixed multiple bugs on the way. Could you if you are still interested in fixing this issue, could you try out the 1.4.2-beta version?
