### ISSUE TITLE
Cannot pack all files into .blend due to missing black.png file

### ISSUE THREAD

**Issue by syworks16** [PhysicalAddons/physical-starlight-and-atmosphere#41]
I am unable to pack my external files when add on is installed, due to this file: 

 'C:\Users\_____\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\physical-starlight-atmosphere\textures\black.png' not found

**Comment by karlisup** [comment]
Hi @syworks16,
Thank you for your patience and sorry it took so long to get back to you! For a while, we have dropped the usage of _black.png_ which should solve this problem. Have you tried using a newer PSA addon version 1.3.1 or 1.4.2-beta?
