### ISSUE TITLE
Not a Bug: Any pointers for the beta Cloud settings?

### ISSUE THREAD

**Issue by quadcom** [PhysicalAddons/physical-starlight-and-atmosphere#42]
Jumped in when I saw the cloud generator. This is something I've been looking for for a while.

Played with all the settings and I can't seem to see any effect on anything. 

Any pointers on the settings or are there a special settings in Cycles that I'm missing?

![image](https://user-images.githubusercontent.com/7085931/122946937-c66b6d80-d347-11eb-9fed-ef75b285667f.png)

**Comment by martinsh** [comment]
Yes, Clouds are visible only in Eevee 'out of the box'.
It will be fixed in non-Beta version.
Meanwhile you can enable clouds for Cycles in world node editor like this:

![IMG_20210620_024437](https://user-images.githubusercontent.com/11915915/123087846-af9f4680-d42d-11eb-844a-68caf3125a1c.jpg)

**Comment by quadcom** [comment]
So the default node layout doesn't work? It almost looks like it's doing the same thing to me.

![image](https://user-images.githubusercontent.com/7085931/123141653-9e9f0700-d426-11eb-9fa2-81c061facb72.png)

**Comment by martinsh** [comment]
exactly the same thing! :) but Cycles does not like it.

**Comment by Lampenbauer** [comment]
Duplicate issue: https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/49

**Comment by karlisup** [comment]
This is now fixed in v1.4.2
