### ISSUE TITLE
Starlight v 1.3.1 - switch from earth preset to Nishita and back to earth - lose controls in World tab

### ISSUE THREAD

**Issue by kylefoxaustin** [PhysicalAddons/physical-starlight-and-atmosphere#44]
**Describe the bug**
[Replace this with a clear and concise description of what the issue is about.]

**General information**
- Blender version: 2.93.0 
- Addon version: 1.3.1 
- Engine: Cycles 
- Operating System: Windows 10  
- Other info that could be useful:  

**To Reproduce**
Launch Blender.
Go to World tab
Turn on Physical Atmosphere (if not enabled yet)
- You will see all the settings for Sun, Atmosphere, Stars, Ground...
Switch preset to Nishita
- all settings disappear under those categories (which I believe is by design)
Switch preset to Earth
- Settings are still gone, no obvious way to bring them back 

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![preset bug](https://user-images.githubusercontent.com/13992031/124338012-445f1e00-db6b-11eb-871c-d945f4cf9f10.png)

**Comment by karlisup** [comment]
Hi @kylefoxaustin,
Thank you for your patience! I was just trying to reproduce the issue on
Blender version: 2.93.1
Addon version: 1.3.1
following your mentioned steps, but I couldn't. Is this issue still bothering you? If it is - could you open  System Console (On Windows 10 Blender under `Window > Toggle System Console`) and see if it gives you any error?

**Comment by karlisup** [comment]
I will close this issue due to inactivity and fact that we cannot reproduce it.
