### ISSUE TITLE
Addon crashing while switching presets

### ISSUE THREAD

**Issue by soumikam** [PhysicalAddons/physical-starlight-and-atmosphere#46]
**Describe the bug**
[Replace this with a clear and concise description of what the issue is about.]

**General information**
- Blender version: [e.g. 2.3.1]
- Addon version: [e.g. 1.3.0]
- Engine: [e.g. Eevee or Cycles]
- Operating System: [Windows 10]
- Other info that could be useful: [e.g. CPU, GPU, etc.]: 

**To Reproduce**
1. Opened the scene.
2. Ticked Physical Starlight checkbox in world settings.
3. No issues when changing the "Earth" parameters.
4. On switching to any other presets, following error occurs.

Python: Traceback (most recent call last):
  File "C:\Users\Soumik\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\physical-starlight-atmosphere\ui.py", line 228, in draw
    stars_type = asettings.stars_type
AttributeError: 'DynamicProperties' object has no attribute 'stars_type'

location: <unknown location>:-1

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![image](https://user-images.githubusercontent.com/54310378/125052054-30627180-e0c1-11eb-8b90-147d263fd0f0.png)

**Comment by karlisup** [comment]
Hi @soumik-devil,
Thank you for your patience and sorry it took 2 months to reply to your ticket! I just tried to reproduce it and could not, but it seems like a setup/update issue. Whenever updating to a new addon version sometimes this issue occurs. If this issue persists try following this [troubleshooting procedure](https://www.physicaladdons.com/psa/updating/#troubleshooting) to fix it.

P.S. by saying `Blender version: [e.g. 2.3.1]` do you mean Blender version 2.9.1?

**Comment by soumikam** [comment]
Hi @karlisup,
No problem for the delay. I used the addon in Blender 2.90.1 and it worked fine there. It seems like a version mismatch issue, I guess. 
The addon is great and I made my recent render using the addon in Blender 2.90.1.
https://www.instagram.com/p/CTkFULDJtgD/ - This is the link to the render if you want to check it out.

Yeah, I mean 2.9.1 (my mistake there).

**Comment by karlisup** [comment]
Looks wonderful! Thank you for sharing your work with us.
