### ISSUE TITLE
Can't find clouds tab

### ISSUE THREAD

**Issue by raitan2008** [PhysicalAddons/physical-starlight-and-atmosphere#48]
Running the new cloud update and I can't find anything on the N tab for clouds. Running blender 2.93.1

**Comment by raitan2008** [comment]
I fixed it. I uninstalled the old 1.3 first, then installed the 1.4...now I see the physical clouds in the N tab.

**Comment by raitan2008** [comment]
ok...I found the tab for clouds, but it does nothing. Am I missing something again? Can we get a quick tutorial on how to initialize the cloud system. I have the physical clouds checked.

**Comment by karlisup** [comment]
Hi @raitan2008,
Try this approach:
1. Enable addon
2. Enable Atmosphere
3. Enable Clouds

We'll re-think how this should work when we release the stable version.  
![image](https://user-images.githubusercontent.com/3999661/127848159-2c1738dc-1a14-4935-b9df-38f35a543107.png)

Let me know if this works for you.

**Comment by raitan2008** [comment]
I did all of that. I can see a semblance of clouds, especially in EEVee, but I get nothing like the results I see in the ads. 
    On Monday, August 2, 2021, 05:37:21 AM CDT, Karlis Upitis ***@***.***> wrote:  
 
 


Hi @raitan2008,
Try this approach:
   
   - Enable addon
   - Enable Atmosphere
   - Enable Clouds

We'll re-think how this should work when we release the stable version.


Let me know if this works for you.

**Comment by raitan2008** [comment]
here is the screen shots of my UI. This is the look I get. The last one is from EEVEE, which I can see a semblance of clouds, but nowhere near what I am supposed to get.
    On Tuesday, August 3, 2021, 08:46:00 AM CDT, D. Eric Harmon ***@***.***> wrote:  
 
  I did all of that. I can see a semblance of clouds, especially in EEVee, but I get nothing like the results I see in the ads. 
    On Monday, August 2, 2021, 05:37:21 AM CDT, Karlis Upitis ***@***.***> wrote:  
 
 


Hi @raitan2008,
Try this approach:
   
   - Enable addon
   - Enable Atmosphere
   - Enable Clouds

We'll re-think how this should work when we release the stable version.


Let me know if this works for you.

**Comment by raitan2008** [comment]
I am using the latest version of blender with an RTX 2980 ti and my drivers are up to date.
    On Tuesday, August 3, 2021, 08:58:19 AM CDT, D. Eric Harmon ***@***.***> wrote:  
 
  
here is the screen shots of my UI. This is the look I get. The last one is from EEVEE, which I can see a semblance of clouds, but nowhere near what I am supposed to get.
    On Tuesday, August 3, 2021, 08:46:00 AM CDT, D. Eric Harmon ***@***.***> wrote:  
 
  I did all of that. I can see a semblance of clouds, especially in EEVee, but I get nothing like the results I see in the ads. 
    On Monday, August 2, 2021, 05:37:21 AM CDT, Karlis Upitis ***@***.***> wrote:  
 
 


Hi @raitan2008,
Try this approach:
   
   - Enable addon
   - Enable Atmosphere
   - Enable Clouds

We'll re-think how this should work when we release the stable version.


Let me know if this works for you.

**Comment by karlisup** [comment]
Hi @raitan2008,
Could you please try re-uploading the screenshots of your UI? Unfortunately, they do not appear here on GitHub chat.
![image](https://user-images.githubusercontent.com/3999661/129070952-2ba1e828-35c1-459f-a867-8f2eae61b111.png)

**Comment by karlisup** [comment]
Will close this issue due to inactivity. Feel free to reopen it.

**Comment by raitan2008** [comment]
I still have this issue. the clouds don't work. I sent an image of what was going on and my settings.    On Wednesday, August 11, 2021, 11:56:53 AM CDT, Karlis Upitis ***@***.***> wrote:  
 
 


Hi @raitan2008,
Could you please try re-uploading the screenshots of your UI? Unfortunately, they do not appear here on GitHub chat.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by karlisup** [comment]
Hi @raitan2008,
Could you try out the addon 1.4.2-beta version and report if the issue still persists?
![image](https://user-images.githubusercontent.com/3999661/132536749-1622a7ae-ce68-470f-a1e8-168f8d99182c.png)
This should fix the issue where the _Cloud_ tab cannot be found as we removed it and integrated it into the _Atmosphere_ tab for this version to remove the confusion.

**Comment by raitan2008** [comment]
I already tried it, and the issue is gone. Thank you for the follow up.
    On Monday, October 18, 2021, 05:23:35 AM CDT, Karlis Upitis ***@***.***> wrote:  
 
 


Closed #48.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
