### ISSUE TITLE
Issue with Clouds in Cycles

### ISSUE THREAD

**Issue by AlstonJones** [PhysicalAddons/physical-starlight-and-atmosphere#49]
**Describe the bug**
Cannot find settings where I can see distinct clouds.  The same settings in Eevee which show distinct clouds will only show diffused light effects and no amount of tweaking to the settings has given me good results.  

**General information**
- Blender version:  2.9.3
- Addon version: 1.4.1]
- Engine: Cycles
- Operating System: Windows 10
- Other info that could be useful: [e.g. CPU, GPU, etc.]:  RTX 3070, Intel i7-7700K, 64 GB RAM

**To Reproduce**
Create visibly distinct clouds in Eevee.  Switch to Cycles and try to set up clouds in a similar way.  

**Screenshots**
![image](https://user-images.githubusercontent.com/43013869/127878915-461a9280-0e52-48e9-ab30-572d17901a28.png)
![2](https://user-images.githubusercontent.com/43013869/127879329-b56c35bc-49d2-4b12-8627-4a8ed6217487.png)
![untitled2](https://user-images.githubusercontent.com/43013869/127879347-f06e9a4e-58e3-44fc-a894-7da3e10e51fb.png)

**Comment by Lampenbauer** [comment]
Why was this closed? Issue is still present.

**Comment by AlstonJones** [comment]
There is another ticket I saw that addresses this.  You have to go in and change thenode setup in the world shader.

**Comment by Lampenbauer** [comment]
Why don't you link the other issue and also link the solution or go a bit more into detail about what there is to do with the world shader. This is terrible git issue handling!

**Comment by Lampenbauer** [comment]
Issue duplicate with temporary solution: https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/issues/42

**Comment by AlstonJones** [comment]
I'm no expert in git hub etiquette. I came here to seek help/ offer whatever help I could.  I'm sorry I didn't go through the proper procedures.  Luckily you are here to fix everything.

**Comment by Lampenbauer** [comment]
@AlstonJones I see! Sorry that I was a bit harsh in my reply yesterday!
