### ISSUE TITLE
V1.2 atmosphere not automated in 2.8

### ISSUE THREAD

**Issue by Dypierpo** [PhysicalAddons/physical-starlight-and-atmosphere#5]
**Describe the bug**
To achieve fog atmospheric effect on objects, starlight node must be linked to every visible material in Blender 2.8 scene. Adjusting atmosphere density, height, or intensity does not affect objects in scene without manually applying starlight node to each materials in either Cycles or Eevee engine. 

**General information**
- Blender version: 2.8.2
- Engine: Evee and Cycles
- Operating System: Windows 10
- Other info that could be useful: CPU-i7-8700K, GPU-GTX1080ti, 64GB G.skill ram

**Screenshots**
Automated when first turning on Ahysical Starlight and Atmosphere addon
![Automated](https://user-images.githubusercontent.com/64932999/81486595-9ed04900-920a-11ea-8eff-3cd7e2d5e4e7.jpg)

Fog visible only when manually applying Starlight node to all 11 materials in the scene
![Manual](https://user-images.githubusercontent.com/64932999/81486599-a394fd00-920a-11ea-9b51-6884ee6b30e8.jpg)

**Comment by martinsh** [comment]
Hello, try "toggle material fog" button. Auto fog is not enabled by default.
https://starlight-manual.readthedocs.io/en/1.2/fog/

**Comment by Dypierpo** [comment]
> Hello, try "toggle material fog" button. Auto fog is not enabled by default.
> https://starlight-manual.readthedocs.io/en/1.2/fog/

Gah! Apologies. Thought it was enabled by default with this update. Thanks so much!
