### ISSUE TITLE
Volume Scatter

### ISSUE THREAD

**Issue by garin210** [PhysicalAddons/physical-starlight-and-atmosphere#50]
**Describe the bug**
i'm following a tutorial(jama's beginning of blender tutorial) and he uses atmosphere and volume scatter to create god's ray effect. but when I add volume scatter the scene creates artifacts and doesn't respond well.

**General information**
- Blender version: 2.93.1
- Addon version: 1.4.1
- Engine:Evee 
- Operating System: macOS(big sir)

<img width="1587" alt="Screen Shot 2021-08-20 at 5 58 05 PM" src="https://user-images.githubusercontent.com/43484734/130305593-4cc3d9d5-9af8-46bd-8acf-02d9fa2ba5ea.png">

**Comment by karlisup** [comment]
Hi @garin210,
Thank you for your patience! Had a conversation with @martinsh and we tried to reproduce this issue, but we could not. Here is the outcome:
![image](https://user-images.githubusercontent.com/3999661/132366113-7b0a7b27-f8a8-4195-93e4-2b85673be18c.png)
I assume that we are missing out on some properties or scene settings that were provided in Jama's beginning of blender tutorial. Are there any more steps we should take than these?
1. Open blender 
2. Enable Physical Starlight and Atmosphere v1.4.1
3. Open World shader editor and add Volume Scatter properties (with values you provided)
4. Open it in the camera mode
