### ISSUE TITLE
World goes black on new load

### ISSUE THREAD

**Issue by iconnorthomas** [PhysicalAddons/physical-starlight-and-atmosphere#52]
**Describe the bug**
I created four different scenes with different Atmosphere World data. Then I rendered out a first pass of my animation once I was happy with it. I loaded the blender scene again today, but the world is completely black. I managed to get the sky to appear with the clouds, but the colors are all different now and the materials in the world aren't being lit by it. This might be because the sun disk isn't appearing anymore either.

**General information**
- Blender version: 2.91.2
- Addon version: 1.4.1
- Engine: Eevee (but also in Cycles I checked)
- Operating System: Windows 10 Pro
- Other info that could be useful: [e.g. CPU, GPU, etc.]: Intel i7-10700K CPU @ 3.80GHz, 32 GB installed ram, NVIDIA GeForce RTX 2080 SUPER

**To Reproduce**
-Created scene with atmosphere
-Rendered Scene
-Created another scene with a lighting setup with density increased so I can comp this later in AE
-Rendered other scene
-Close blender
-Open blender
-Disable Physical Atmosphere in World options
-Enable Physical Atmosphere in World options(this would at least show the sky at this point.

**Screenshots**
First open to see this
![Screenshot 2021-09-05 124108](https://user-images.githubusercontent.com/46064861/132139439-7f603c21-4931-4be9-8109-609916ac915a.png)

After troubleshooting the best I could I got the sky to appear
![Screenshot 2021-09-05 123911](https://user-images.githubusercontent.com/46064861/132139365-9d123570-e398-4d1e-8718-1efa9e6eb863.png)

What is should look like
![Screenshot 2021-09-05 124232](https://user-images.githubusercontent.com/46064861/132139481-81a5cfb9-7e8d-4b1a-9f53-3b0c901ec49d.png)

**Comment by karlisup** [comment]
Hi @iconnorthomas,
We did try twice to replicate this issue and without any success. My assumption I that it could somehow be related to your scene setup and functions that trigger scene change. Could you send the _.blend_ file for investigation or create one that has the same issue?

Does this issue persist if you try it on PSA v1.4.2?

**Comment by karlisup** [comment]
I'll close this for now as this has been inactive for more than a month.
