### ISSUE TITLE
Addon Not Responding

### ISSUE THREAD

**Issue by Tesotron** [PhysicalAddons/physical-starlight-and-atmosphere#55]
Has anybody had an issue where the Addon has simply stopped responding during a session? I can still punch in numbers and move scales but there are no updates.

On 1.4.2 the clouds still respond, i.e. I can change the scale, but the rest of the options have no effect. 
On 1.3.1 Nothing is responsive when this occurs.

Restarting doesn't solve it, and reinstalling the app does nothing either, after a while the issue shows up again in random times, i..e. I'm using no other addons and just playing with lighting on a cube and I can still replicate it randomly.

**Comment by karlisup** [comment]
Hi @Tesotron ,
Can you check if the Blender console is reporting any errors? Which Blender version are you using?

**Comment by karlisup** [comment]
I will close the issue as inactive. Feel free to add more details so we can investigate this further if the issue persists.
