### ISSUE TITLE
Rotating the sun in the viewport on the X and the Y axis is glitchy

### ISSUE THREAD

**Issue by ogierm** [PhysicalAddons/physical-starlight-and-atmosphere#6]
**Describe the bug**
When rotating the sun in the viewport it will randomly jump around.

**General information**
- Blender version: 2.8.3
- Engine: all (EEVEE / Cycles / Workbench)
- Operating System: Windows 10
- Other info that could be useful: Core i5 3570K, GTX 970

**To Reproduce**
- Rotate the sunlight on either the x or the y axis in the viewport (not via the azimuth / elevation) panel

**Screenshots**
![2020-05-10_21-43-31](https://user-images.githubusercontent.com/29630575/81509032-22bc2b00-9308-11ea-8dc8-2183d2033dcf.gif)
The gif is quite large, so it may take a few secs to cache before it will be played back smoothly

**Comment by karlisup** [comment]
Hi, @ogierm,
Thank you for your patience! It is interesting that while _playing_ on a daily basis with this addon I did not notice this small _wiggle_. When the sun is moved by gimbal the azimuth and elevation values are updated which then again triggers an update of the sun position which could be the reason for wiggling. I'll prioritize this and put the fix in the next bugfix version.

**Comment by karlisup** [comment]
Fixed in [version 1.2.3](https://starlight-manual.readthedocs.io/en/latest/release-notes/#123-released-20082020).
