### ISSUE TITLE
Mars sky way overexposed; exposure correction = bluish sky

### ISSUE THREAD

**Issue by SongCast** [PhysicalAddons/physical-starlight-and-atmosphere#61]
Hi, I'm loving Physical Starlight And Atmosphere! Fantastic product. Thank you!

I'm experimenting and I've noticed that the default Mars settings yield's a wildly over-exposed result. Adjusting the exposure (via KCyclesX post-processing) yields a nicely exposed image, however the martian sky hue becomes bluish (most real-world images suggest Mars' sky leans toward butterscotch); is this by design? Thanks again.

**System Information**
Operating system: Windows-10-10.0.22000-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 511.23

**Blender Version**
Broken: version: 3.0.1 Release Candidate, branch: K-CyclesX2, commit date: 2022-01-16 20:48, hash: `rB75dde0af07ed`
Worked: (newest version of Blender that worked as expected)

![mars_landscape_kcycles_exposure](https://user-images.githubusercontent.com/95632470/151038299-26122fca-f2c0-4922-8a30-72a718cb8312.jpg)

**Comment by karlisup** [comment]
Hi @SongCast,
Thank you for your reporting the issue. We did reproduce the bug and will fix it shortly.

**Comment by SongCast** [comment]
Here's a follow-up render using PSA v1.5.0, KCyclesX v3.01, Windows 11, default Mars profile, no post-processing. Looking much, much better! Thank you!

![mars_landscape_kcycles_exposure--follow-up](https://user-images.githubusercontent.com/95632470/157083971-f7265b65-f4e4-4a5b-b595-c59e555d47be.jpg)

**Comment by karlisup** [comment]
Thank you for reporting back! I am glad it worked <3
