### ISSUE TITLE
PSA 1.4.4: Binary sun settings not retained

### ISSUE THREAD

**Issue by SongCast** [PhysicalAddons/physical-starlight-and-atmosphere#63]
When I edit settings for the Binary Sun via the Shader tab node editor (Scene > Atmosphere > . PhysicalInputs), the edits are accurately reflected by the Cycles 3D Viewport render preview. However, when I then initiate a full render (F12) the Binary Sun settings immediately revert to the factory default.

It does not matter whether I save the Binary Sun settings to a new PSA preset just after my edits, and/or reload them. In fact, when I examine the just-created new preset, the preset contains the default Binary Sun settings--and not my edits.

One workaround I've had limited success with is to edit the Binary Sun values directly in the *.py preset file and then reload that preset. In that case, the Binary Sun edits are retained.

**System Information**
Operating system: Windows-10-10.0.22000-SP0 64 Bits
Graphics card: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 511.65

**Blender Version**
Broken: version: 3.0.1, branch: master, commit date: 2022-01-25 17:19, hash: `rBdc2d18018171`
Worked: (newest version of Blender that worked as expected)

[earth_binary_py.txt](https://github.com/PhysicalAddons/physical-starlight-and-atmosphere/files/8053603/earth_binary_py.txt)

**Comment by karlisup** [comment]
Hi @SongCast,
Just closed issue regarding mars preset/asset. Could confirm that after v1.5.0 this issue is also gone, please?
