### ISSUE TITLE
version 1.5 won't install

### ISSUE THREAD

**Issue by charliemagee** [PhysicalAddons/physical-starlight-and-atmosphere#67]
On a Macbook Pro, macOS Catalina.

I uninstalled version 1.3.2 before installing new version. Error is attached

<img width="1270" alt="phys-star-atmo-install-error" src="https://user-images.githubusercontent.com/897319/156849846-7c345f41-257d-41fa-82e7-c01a1f66b7cc.png">

**Comment by charliemagee** [comment]
Blender 3.0.0, by the way.

**Comment by karlisup** [comment]
Hi @charliemagee,
Reopening Blender should fix the issue. We are still investigating how to address this issue as Blender caches uninstalled version (if Blender is not reopened) and thus sabotaging the new install. Could you please report if after reopening Blender issue persists?

**Comment by charliemagee** [comment]
That did it. Sorry I didn't think of that myself. Looking forward to playing with the new version. Thanks for making the update free to existing users.

**Comment by karlisup** [comment]
Happy that it worked! Together with the team will try to figure out how fix this annoying bug as it is as old as our addon updates. Cheers and hope that you'll enjoy it!

**Comment by charliemagee** [comment]
Maybe add a README to the download? I think a lot of people, including me, read those before doing a new install. OR is there a way to post that alongside the little checkbox that turns it on? Or during the uninstall of the previous version? Or maybe a message in the settings of the Addon itself, that announces the update and reminds for the restart?

I use Extreme PBR material addon and they put a big RED message at the top of the settings panel.

**Comment by karlisup** [comment]
I am always looking for the _silver bullet_ and forgetting that a simple README at least temporarily could do the trick. Thank you for the suggestions, Charlie! Will discuss this with the team at Monday's standup meeting. Have a wonderful weekend!

**Comment by charliemagee** [comment]
You have a great weekend too! I'll be messing around with clouds and fog colors!
