### ISSUE TITLE
Animating via Sunposition-Addon gives same Frame in Output 

### ISSUE THREAD

**Issue by threesixtyat** [PhysicalAddons/physical-starlight-and-atmosphere#7]
The Sunposition-Addon updates the Sun and Atmosphere nice in the Viewport but when you animating Time (via keyframing with the sunpositions-addon) the outputframes don't update.

**General information**
- Blender version: 2.83.12 (e-cycles)
- Engine: Eevee
- Operating System: Windows 10
- Other info that could be useful: i5 8600K, GTX 1080ti, 64gb ram

Set time in sunposition-addon to 0, add keyframe, set time to 23, add keyframe, render animation.
i tried to insert one frame between with toogle physical atmosphere off and on to hope it refreshes inbetween the frames...... :-) work [stupid workaround]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Comment by s-leger** [comment]
The workaround is to set hours by hand, select sun and add keyframes to sun location / rotation at relevant rate.

**Comment by karlisup** [comment]
Hi @threesixtyat,
Thank you for your patience! I did reproduce the bug and prioritized it. Thank you @s-leger for giving the workaround.

**Comment by LennartSolik** [comment]
I dont know if this is related but i also had issues after changing the timescale with the time remapping. After i made a slow motion animation from the same scene i was rendering with some view layers randomly rendered different frames. (jumping from frame 45 to 2 to 126 and so on). I will try to reproduce the bug with Athmosphere only and check if this is a addon related issue.

**Comment by karlisup** [comment]
I managed to fix the time animation issue by fixing #1 and renaming Sun. Still not sure why, but happy that one issue fixed another. @LennartSolik Regarding jumping frames - it would be awesome if you manage to reproduce that. Or you can wait for the bug fix I am to release and check then.

**Comment by karlisup** [comment]
The time animation issue is fixed in [version 1.2.3](https://starlight-manual.readthedocs.io/en/latest/release-notes/#123-released-20082020). Regarding the jumping frames, if you manage to reproduce, could you please open a new ticket for it? Thank you in advance!

**Comment by threesixtyat** [comment]
My Workaround with adding keyframes isn't working anymore.

I just keyframed the time of the sun via sunposition addon.
the sun is moving correctly but the sky don't update every time, only spontaneously.

<blockquote class="imgur-embed-pub" lang="en" data-id="a/NYVzCqV"  ><a href="//imgur.com/a/NYVzCqV">Sunposition</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

Version 1.3.1
E-Cycles 2.93.2

**Comment by karlisup** [comment]
Hi @threesixtyat,
Managed to reproduce described behavior. Currently, it's possible to animate the sun using azimuth/elevation properties and sun object (rotation parameter), but when using Sun Position addon results are unclear. Investigating this issue and will report my findings.

**Comment by karlisup** [comment]
Hi!
My findings were that 1st frame is the same as 2nd one, but all other frames are correctly rendered. Was that your experience too?
> Currently, it's possible to animate the sun using azimuth/elevation properties and sun object (rotation parameter), but when using Sun Position addon results are unclear.

This behavior is weird and hard to figure out a reason why it is not working as implemented on our side. Regarding the following steps - I'll try to reach out to Sun Position addon developers and figure out the possible reasons.

**Comment by hnoerenberg** [comment]
I have a similar problem. In my animation the sun is jumping around when rendered over Deadline / Render Manager. (I used Shot-Manager to submit the Shots)
When I render with an open Blender (Render-Animation) everything seems to work like expected. I got some weird console-errors regarding a sun upper- something yesterday but was to stupid to copy the error log.

**Comment by karlisup** [comment]
Hi @threesixtyat  & @hnoerenberg,
There were multiple issues causing this particular bug. Could you, please test out 1.4.2beta and report if the issue still persists?
